### ISSUE TITLE
Pool Fee Percent not set in Muesliswap & Sundaeswap liquidityPoolFromUtxo method

### ISSUE THREAD

**Issue by dpbeaumont** [IndigoProtocol/dexter#29]
When going from a utxo to liquidityPool using the method `liquidityPoolFromUtxo` for Muesli & Sundaeswap I have noticed the pool returned always has a 0 `poolFeePercent`.  This means later when we act on the on the SwapRequest, calling `estimatedReceive` which takes into account the poolFeePercent for the estimated output calculation , the amount is then incorrect. 

Screenshot below comparing wingriders to minswap.
![image](https://github.com/IndigoProtocol/dexter/assets/49551821/cdd4ceb2-dc65-4a36-951c-6d76b37b655b)

This is also not present on Sundaeswap,

**Comment by Sluder** [comment]
@dpbeaumont The populated data for a pool can be limited when constructing just from the pool UTxO. In this case, Muesli provides the pool fees in a different UTxO datum https://github.com/IndigoProtocol/dexter/blob/master/src/dex/muesliswap.ts#L64. Whenever the pool fee is hardcoded like you are seeing, this is because that data isn't provided when constructing a pool from on-chain data.

**Comment by Sluder** [comment]
Will be resolved once https://github.com/IndigoProtocol/dexter/pull/35 goes in

**Comment by dpbeaumont** [comment]
Confirmed fixed. Cannot replicate now! Thanks
